name: Testes de API com Rest Assured

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código-fonte
      uses: actions/checkout@v2

    - name: Configurar o ambiente Java
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Instalar o Apache Maven
      run: |
        sudo apt update
        sudo apt install maven -y

    - name: Executar testes de API
      run: mvn test