name: Automate API Tests
on: [push]  # Dispara o pipeline quando há push para o repositório

jobs:
  build:
    runs-on: ubuntu-latest  # Ação será executada em um ambiente Ubuntu

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: main
        path: DesafioAutomacaoAPI/DesafioAutomacaoAPI
        
    - name: Set up JDK 11  # Passo para configurar o ambiente Java (Java Development Kit)
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Use a versão do JDK necessária para o projeto
        distribution: 'adopt'
    - name: Install Maven
      run: |
        sudo apt update
        sudo apt install maven
      
    - name: Run API Tests  # Passo para executar os testes de API
      run: |
        cd /home/runner/work/DesafioAutomacaoAPI/DesafioAutomacaoAPI/pom.xml
        mvn test  # Este comando deve ser ajustado com o comando real para executar os testes em seu projeto

    - name: Publish Test Results  # Passo para publicar resultados dos testes
      if: always()  # Será executado mesmo se houver falha nos testes
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/cucumber-reports  # Verifique o caminho real para seus relatórios de testes

    # Outros passos, como notificação ou implantação, podem ser adicionados aqui
